Repository Deltares/Ribasim, pull requests merged in 2024-04, with the labels that each got.

#1371 Support conditions on linear combinations of variables for `DiscreteControl`
  core/src/callback.jl
  core/src/parameter.jl
  core/src/read.jl
  core/src/schema.jl
  core/src/util.jl
  core/src/validation.jl
  core/test/control_test.jl
  docs/core/usage.qmd
  docs/python/examples.ipynb
  python/ribasim/ribasim/config.py
  python/ribasim/ribasim/model.py
  python/ribasim/ribasim/nodes/discrete_control.py
  python/ribasim/ribasim/schemas.py
  python/ribasim/tests/test_io.py
  python/ribasim_testmodels/ribasim_testmodels/__init__.py
  python/ribasim_testmodels/ribasim_testmodels/allocation.py
  python/ribasim_testmodels/ribasim_testmodels/discrete_control.py
  python/ribasim_testmodels/ribasim_testmodels/dutch_waterways.py
  python/ribasim_testmodels/ribasim_testmodels/invalid.py
  python/ribasim_testmodels/ribasim_testmodels/pid_control.py
  ribasim_qgis/core/nodes.py
Labels: breaking

#1436 Precalculate resistance neighbors
  core/src/allocation_init.jl
  core/src/callback.jl
  core/src/parameter.jl
  core/src/read.jl
  core/src/solve.jl
  core/src/util.jl
  core/src/validation.jl
  core/test/validation_test.jl
  python/ribasim_testmodels/ribasim_testmodels/invalid.py
Labels: performance

#1433 Update vertical fluxes all at once
  core/src/callback.jl
  core/src/solve.jl
Labels: performance

#1434 Tighten edge validation
  core/src/parameter.jl
  core/src/validation.jl
  docs/contribute/addnode.qmd
  docs/python/examples.ipynb
Labels: validation
